<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2014-08-08 22:57:12
 * @@Modify Date: 2017-02-10 09:33:34
 * @@Function:
 */
 ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $helpLabels = $this->helper('alothemes/labels');
?>

<div class="mage-magictabs mc-<?php echo $this->getType();?>">
    <?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <?php 
        $config = $this->getWidgetCfg(); 
        $width  = $config['widthImages'];
        $height = $config['heightImages'];
        $actions = isset($config['action']) ? $config['action'] : array();
    ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_rowCount = isset($config['row']) ? $config['row'] : 1; //$this->getColumnCount(); ?>
    <?php $j=0; $time = isset($config['productDelay']) ? $config['productDelay'] : 0; ?>
    <?php $tag = ($_rowCount >1) ? 'div' : 'ul'; ?>
    <<?php echo $tag ?> class="flexisel-content products-grid <?php echo $this->getType();?> zoomOut play">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($_rowCount > 1 && $i++%$_rowCount==0): ?>
            <ul class="products-grid-rows">
        <?php endif ?>
            <?php $t = $j*$time; $t .='ms'; $j++; ?>

                <li style="<?php echo "-webkit-animation-delay:$t;-moz-animation-delay:$t;-o-animation-delay:$t;animation-delay:$t" ?>;" class="item item-animate">
                    <div class="per-product clearfix">
                        <div class="images-container">
						    <div class="product-hover">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
									<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							    </a>
							</div>
                        </div>
    				</div>
                </li>
            <?php if ($_rowCount > 1 && $i%$_rowCount==0 || $i==$_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
    </<?php echo $tag; ?>>
<?php endif; ?>
</div>


